name: Bug Report
description: Report a reproducible bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please provide clear reproduction details.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Describe the bug in one short paragraph.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Include exact steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser, Node version, app mode
    validations:
      required: true
